#server:
#  port: 8080 #comment out this configuration because of adding it with -Dserver.port=8080 in VM options
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          name: springboot-sample-demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

custom:
  mybatisPlus:
    performance:
      enable: true
  log:
    result: false
#    enable: false

#override the method WebSecurityConfigurerAdapter.configure(AuthenticationManagerBuilder auth),the following configurations fails
#spring:
#  security:
#    user:
#      name: actuator
#      password: actuator
#      roles: ACTUATOR_ADMIN