server:
  servlet:
    context-path: /api/demo
  port: 8080 #comment out this configuration because of adding it with -Dserver.port=80 in VM options

spring:
  application:
    name: springboot-sample-demo
  boot:
    admin:
      client:
        url: http://admin-service-address:8081
        username: admin
        password: admin
        instance:
#          name: springboot-sample-demo
          metadata:
            user.name: actuator
            user.password: actuator
  datasource:
    mysql:
      url: jdbc:mysql://mysql-service-address:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
      username: root
      password: PASS(TXlzcWwxMjNDb25kdWN0b3I=)
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        # 连接池名
        pool-name: MySQL_HikariCP
        # 最小空闲连接数
        minimum-idle: 10
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 600000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 3000
        # 连接测试query
        connection-test-query: SELECT 1
    clickhouse:
      url: jdbc:clickhouse://ck-service-address:8123/default
      username: clickhouse
      password: PASS(Y2xpY2tob3VzZTEyM2FkbWlu)
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      hikari:
        # 连接池名
        pool-name: CK_HikariCP
        # 最小空闲连接数
        minimum-idle: 2
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 600000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 3000
        # 连接测试query
        connection-test-query: SELECT 1
  flyway:
    url: ${spring.datasource.mysql.url}
    user: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录，多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration/mysql
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: t_flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表，在执行 flyway migrate 命令之前，必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候，自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号，默认值为 1，低于该版本号的 SQL 文件，migrate 时会被忽略
    baseline-version: 1
    # 字符编码 默认 UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移，开发建议 true，生产建议 false
    out-of-order: false
    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
    schemas: demo
    # 执行迁移时是否自动调用验证，当版本不符合逻辑会抛出异常
    validate-on-migrate: true
  rabbitmq:
    host: rabbitmq-service-address
    port: 5672
    username: rabbitmq
    password: PASS(cmFiYml0bXExMjNhZG1pbg==)
    virtual-host: /
    publisher-confirms: true  # 开启confirms回调 P -> Exchange，默认false
    publisher-returns: true   # 开启returnedMessage回调 Exchange -> Queue，默认false
    listener:
      simple:
        acknowledge-mode: manual  # 设置手动确认(ack) Queue -> C
        prefetch: 1 #消费者每次从队列获取的消息数量，如果有事务的话，必须大于等于transaction数量
        concurrency: 4  #消费者数量
        max-concurrency: 8  #最大消费者数量
    connection-timeout: 10s #连接超时时间
    requested-heartbeat: 3s #心跳超时时间
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: redis-service-address
    port: 6379
    password: PASS(UmVkaXMxMjNDb25kdWN0b3I=)
    database: 0
    cachePrefix: 'SJD:'
    lettuce:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制），默认8
        max-idle: 8     #连接池中的最大空闲连接，默认8
        min-idle: 2     #连接池中的最小空闲连接，默认0
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制），默认-1ms
    timeout: 10s        #连接超时时间
  profiles:
    active: test

grpc:
  server:
    port: 28080
  client:
    stockQuote:
      host: localhost
      port: 28080

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus,loggers'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    shutdown:
      enabled: false
    health:
      probes:
        enabled: true
      show-details: always

custom:
  decrypt:
    property:
      key: spring.datasource.mysql.password,spring.datasource.clickhouse.password,spring.redis.password,spring.rabbitmq.password
      prefix: PASS(
      suffix: )
  log:
    additional-skip-pattern: /|/ping
    result: true
#    enable: false

#override the method WebSecurityConfigurerAdapter.configure(AuthenticationManagerBuilder auth),the following configurations fails
#spring:
#  security:
#    user:
#      name: actuator
#      password: actuator
#      roles: ACTUATOR_ADMIN

---
spring:
  profiles: test

custom:
  swagger:
    csrf:
      enable: true

---
spring:
  profiles: prod

custom:
  swagger:
    enable: false