apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: springboot-sample-demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-sample-demo
  template:
    metadata:
      labels:
        app: springboot-sample-demo
    spec:
      hostAliases:
        - ip: "172.16.0.4"
          hostnames:
            - "mysql-service-address"
            - "admin-service-address"
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: springboot-sample-demo
          image: baiduyun.com/springboot-sample-demo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: http
              path: /ping
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 2
          args: ["--spring.datasource.password=mysql123root"]
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug
              containerPort: 9090
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9090 -Dspring.datasource.druid.stat-view-servlet.allow="

---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: springboot-sample-demo-svc
spec:
  selector:
    app: springboot-sample-demo
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080
    - name: debug
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 9090
