apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: springboot-sample-demo-deploy
  labels:
    app: springboot-sample-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-sample-demo
  template:
    metadata:
      labels:
        app: springboot-sample-demo
    spec:
      hostname: springboot-sample-demo
      hostAliases:
        - ip: "172.16.0.4"
          hostnames:
            - "mysql-service-address"
            - "redis-service-address"
            - "rabbitmq-service-address"
            - "admin-service-address"
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: springboot-sample-demo
          image: baiduyun.com/springboot-sample-demo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-Djava.security.egd=file:/dev/./urandom -Dspring.datasource.druid.stat-view-servlet.allow="
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: mysqlUser
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: config-secret
                  key: mysqlPassword
          resources:
            limits:
              cpu: 1000m
              memory: 768Mi
            requests:
              cpu: 50m
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "10" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: upload-data-volume
              mountPath: /tmp/upload
      volumes:
        - name: upload-data-volume
          hostPath:
            path: /data/upload
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: springboot-sample-demo-svc
spec:
  selector:
    app: springboot-sample-demo
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080
